### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChillVibesMushroom** [6e726d/chopping#1]
Since this performs channel hopping can you give me a little insight on that? I know that airodump-ng uses --cswitch methods to channel hop...what tools would you use chopping with I like your tool and I might use it

**Comment by 6e726d** [comment]
tcpdump, wireshark, shark or any other network tool that doesn't perform channel hopping.

**Comment by ChillVibesMushroom** [comment]
so basically theres an alternative to airodump-ng o.o

**Comment by 6e726d** [comment]
airodump-ng does much more than channel hopping. This tool just does channel hopping.

**Comment by ChillVibesMushroom** [comment]
How would I use it with airodump-ng though like if airodump-ng method isn't working for me how would I go about doing something like DOS Pursuit when deauthenticating my wifi in order to capture the eapol because using 1 nic isn't working I need two

**Comment by 6e726d** [comment]
I'm not sure. Maybe you can get help on the Aircrack-ng project site.
